== 中医馆业务模型分析

=== 概念模型分析

==== 医馆模型


.医馆模型示意图
[plantuml, entity000, png]
....
@startuml
' hide the spot
hide circle
' avoid problems with angled crows feet
skinparam linetype ortho

entity "医馆基本信息" as e01 {
    *医馆ID <PK>
    --
    *医馆名称
     其他属性
}

entity "药房基本信息" as e02 {
    *药房ID <PK>
    --
    *药房名称
     医馆ID <FK>
     其他属性
}

entity "库房基本信息" as e03 {
    *库房ID <PK>
    --
    *库房名称
     医馆ID <FK>
     其他属性
}

entity "部门基本信息" as e04 {
    *部门ID <PK>
    --
    *部门名称
     医馆ID <FK>
     分店ID <FK>
     上级部门 <FK>
     其他属性
}
entity "分店基本信息" as e05 {
    *分店ID <PK>
    --
    *分店名称
     医馆ID <FK>
     其他属性
}

e01 ||..|{ e02
e01 ||..|{ e03
e01 ||..|{ e04
e01 ||..|{ e05
e04 ||..|{ e04
e04 }|..|| e05
@enduml
....


==== 库房模型


.库房模型示意图
[plantuml, entity001, png]
....
@startuml
' hide the spot
hide circle
' avoid problems with angled crows feet
skinparam linetype ortho

entity "库房基本信息" as e01 {
    *库房ID <PK>
    --
    *库房名称
     医馆ID <FK>
     其他属性
}

entity "库存信息" as e02 {
    *库存ID <PK>
    --
    *库存名称
     医馆ID <FK>
     库房ID <FK>
     物品ID <FK>
     物品名称
     入库单ID <FK>
     剩余库存
     其他属性
}

entity "入库单信息" as e03 {
    *入库单ID <PK>
    --
    *入库单名称
     医馆ID <FK>
     库房ID <FK>
     物品ID <FK>
     物品名称
     入库单状态
     创建人 <FK>
     创建时间
     审核人 <FK>
     审核时间
     审核返回原因
     财务审核人 <FK>
     财务审核时间
     财务审核返回原因
     其他属性
}

entity "入库单明细信息" as e04 {
    *入库单明细ID <PK>
    --
     医馆ID <FK>
     库房ID <FK>
     物品ID <FK>
     入库单ID <FK>
     物品名称
     入库来源
     入库数量
     计量单位
     单价
     金额
     生产日期
     有效日期
     保质期
     其他属性
}


entity "出库单信息" as e05 {
    *出库单ID <PK>
    --
    *出库单名称
     医馆ID <FK>
     库房ID <FK>
     物品ID <FK>
     物品名称
     出库单状态
     创建人 <FK>
     创建时间
     审核人 <FK>
     审核时间
     审核返回原因
     财务审核人 <FK>
     财务审核时间
     财务审核返回原因
     其他属性
}

entity "出库单明细信息" as e06 {
    *出库单明细ID <PK>
    --
     医馆ID <FK>
     库房ID <FK>
     物品ID <FK>
     出库单ID <FK>
     入库单ID <FK>
     物品名称
     调拨单位
     出库数量
     计量单位
     单价
     金额
     生产日期
     有效日期
     保质期
     其他属性
}

e02 }|..|| e03
e03 ||..|{ e04
e03 ||..|{ e06
e05 ||..|{ e06

@enduml
....


==== 小结


=== 物理模型设计


