== 中医馆业务模型分析

=== 概念模型分析

==== 医馆模型

为了方便后续共同交流，我们先对项目设计过程中遇到的一些概念做简要说明。

医馆 :: 这里的医馆市场定位是类似于中医理疗、针灸这样的小型社区诊疗、治疗单位。稍微大一些的链锁分店的概念，在系统建设早期，为了便于快速落地，斩时不考虑医馆分店经营这种模型。简单点来讲，医馆是一个小型医疗企业的概念。在医馆中，库房、药房是两个资产方面的重要概念，我们会在系统中重点研究库房、药房两种场景中的进销存模型。


.医馆模型示意图
[plantuml, entity000, png]
....
@startuml
' hide the spot
hide circle
' avoid problems with angled crows feet
skinparam linetype ortho

entity "医馆基本信息" as e01 {
    *医馆ID <PK>
    --
    *医馆名称
     其他属性
}

entity "药房基本信息" as e02 {
    *药房ID <PK>
    --
    *药房名称
     医馆ID <FK>
     其他属性
}

entity "库房基本信息" as e03 {
    *库房ID <PK>
    --
    *库房名称
     医馆ID <FK>
     其他属性
}

entity "部门基本信息" as e04 {
    *部门ID <PK>
    --
    *部门名称
     医馆ID <FK>
     分店ID <FK>
     上级部门 <FK>
     其他属性
}
entity "分店基本信息" as e05 {
    *分店ID <PK>
    --
    *分店名称
     医馆ID <FK>
     其他属性
}

e01 ||..|{ e02
e01 ||..|{ e03
e01 ||..|{ e04
e01 ||..|{ e05
e04 ||..|{ e04
e04 }|..|| e05
@enduml
....


==== 库房模型

库房是医馆企业用来管理包括药品在内的物质资产的重要场所，比如医疗器材、办公用品、生活物质等。库房管理模型中，物品入、出库、盘盈盘亏，会引起库存的变化，而物品本身是一种实物资产，库存的变化，反映到财务环境中就是资产产值的变化。库房管理模块主要基于这些实际场景展开建模。


.库房模型示意图
[plantuml, entity001, png]
....
@startuml
' hide the spot
hide circle
' avoid problems with angled crows feet
skinparam linetype ortho

entity "库房基本信息" as e01 {
    *库房ID <PK>
    --
    *库房名称
     医馆ID <FK>
     其他属性
}

entity "库房库存信息" as e02 {
    *库存ID <PK>
    --
    *<s>库存名称</s>
     医馆ID <FK>
     库房ID <FK>
     物品ID <FK>
     物品名称
     入库单ID <FK>
     剩余库存
     其他属性
}

entity "库房入库单信息" as e03 {
    *库房入库单ID <PK>
    --
    *库房入库单名称
     医馆ID <FK>
     库房ID <FK>
     物品ID <FK>
     物品名称
     入库来源
     库房入库单状态
     创建人 <FK>
     创建时间
     审核人 <FK>
     审核时间
     审核返回原因
     财务审核人 <FK>
     财务审核时间
     财务审核返回原因
     其他属性
}

entity "库房入库单明细信息" as e04 {
    *库房入库单明细ID <PK>
    --
     医馆ID <FK>
     库房ID <FK>
     物品ID <FK>
     库房入库单ID <FK>
     物品名称
     入库来源
     入库数量
     计量单位
     单价
     金额
     生产日期
     有效日期
     保质期
     其他属性
}


entity "库房出库单信息" as e05 {
    *库房出库单ID <PK>
    --
    *库房出库单名称
     医馆ID <FK>
     库房ID <FK>
     物品ID <FK>
     物品名称
     出库去向
     出库单状态
     创建人 <FK>
     创建时间
     审核人 <FK>
     审核时间
     审核返回原因
     财务审核人 <FK>
     财务审核时间
     财务审核返回原因
     其他属性
}

entity "库房出库单明细信息" as e06 {
    *出库单明细ID <PK>
    --
     医馆ID <FK>
     库房ID <FK>
     物品ID <FK>
     出库单ID <FK>
     库房入库单ID <FK>
     物品名称
     出库去向
     出库数量
     计量单位
     单价
     金额
     生产日期
     有效日期
     保质期
     其他属性
}

e02 }|..|| e03
e03 ||..|{ e04
e03 ||..|{ e06
e05 ||..|{ e06

@enduml
....


==== 药房模型

药房是集中存入、管理药品的场所。药品是医馆企业资产中最为重要的核心资产，药品进销存活动主要围绕药房展开，活动中产生的数据反应了医馆企业药品资产的变化状况。

.药房模型示意图
[plantuml, entity002, png]
....
@startuml
' hide the spot
hide circle
' avoid problems with angled crows feet
skinparam linetype ortho

entity "药房基本信息" as e01 {
    *药房ID <PK>
    --
    *药房名称
     医馆ID <FK>
     其他属性
}

entity "药房库存信息" as e02 {
    *药房库存ID <PK>
    --
    *<s>药房库存名称</s>
     医馆ID <FK>
     药房ID <FK>
     物品ID <FK>
     物品名称
     入库单ID <FK>
     剩余库存
     其他属性
}

entity "药房入库单信息" as e03 {
    *药房入库单ID <PK>
    --
    *入库单名称
     医馆ID <FK>
     药房ID <FK>
     物品ID <FK>
     物品名称
     入库来源
     入库单状态
     创建人 <FK>
     创建时间
     审核人 <FK>
     审核时间
     审核返回原因
     财务审核人 <FK>
     财务审核时间
     财务审核返回原因
     其他属性
}

entity "药房入库单明细信息" as e04 {
    *药房入库单明细ID <PK>
    --
     医馆ID <FK>
     药房ID <FK>
     物品ID <FK>
     药房入库单ID <FK>
     物品名称
     入库来源
     入库数量
     计量单位
     单价
     金额
     生产日期
     有效日期
     保质期
     其他属性
}


entity "药房出库单信息" as e05 {
    *药房出库单ID <PK>
    --
    *出库单名称
     医馆ID <FK>
     药房ID <FK>
     物品ID <FK>
     物品名称
     出库去向
     出库单状态
     创建人 <FK>
     创建时间
     审核人 <FK>
     审核时间
     审核返回原因
     财务审核人 <FK>
     财务审核时间
     财务审核返回原因
     其他属性
}

entity "药房出库单明细信息" as e06 {
    *出库单明细ID <PK>
    --
     医馆ID <FK>
     药房ID <FK>
     物品ID <FK>
     出库单ID <FK>
     入库单ID <FK>
     物品名称
     出库去向
     出库数量
     计量单位
     单价
     金额
     生产日期
     有效日期
     保质期
     其他属性
}

e02 }|..|| e03
e03 ||..|{ e04
e03 ||..|{ e06
e05 ||..|{ e06

@enduml
....



==== 小结


=== 物理模型设计


